const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};
const ACTIVITY_ACTIONS = {
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  VIEW: "VIEW"
};

const RESOURCE_TYPES = {
  WORKFLOW: "WORKFLOW",
  CATEGORY: "CATEGORY",
  TAG: "TAG",
  COMMENT: "COMMENT",
  BOOKMARK: "BOOKMARK"
};

const ACTIVITY_DEFAULTS = {
  DESCRIPTION: ""
};
const WORKFLOW_CATEGORIES = ["GENERAL"];
const WORKFLOW_DIFFICULTY = ["BEGINNER", "INTERMEDIATE", "ADVANCED"];
const WORKFLOW_DEFAULTS = {
  IS_ARCHIVED: false,
  VIEWS: 0,
  LIKES: 0
};

const DASHBOARD_DEFAULTS = {
  RECENT_ACTIVITY_LIMIT: 10,
  SUMMARY_TIMEFRAME_DAYS: 30
};

const TEAM_DEFAULTS = {
  DESCRIPTION: "Team description",
  VISIBILITY: "PUBLIC"
};

const VISIBILITY_OPTIONS = {
  PUBLIC: "PUBLIC",
  PRIVATE: "PRIVATE"
};
// Theme options for the UI
const THEME_OPTIONS = {
  LIGHT: "light",
  DARK: "dark",
  SYSTEM: "system"
};

// Language options supported by the app
const LANGUAGE_OPTIONS = {
  EN: "en",
  ES: "es",
  FR: "fr"
};

// Default preferences values
const PREFERENCES_DEFAULTS = {
  THEME: THEME_OPTIONS.LIGHT,
  TIMEZONE: "UTC",
  EMAIL_NOTIFICATIONS: true,
  LANGUAGE: LANGUAGE_OPTIONS.EN
};


module.exports = {
  HTTP_STATUS,
  ACTIVITY_ACTIONS,
  RESOURCE_TYPES,
  ACTIVITY_DEFAULTS,
  WORKFLOW_CATEGORIES,
  WORKFLOW_DIFFICULTY,
  WORKFLOW_DEFAULTS,
  DASHBOARD_DEFAULTS,
  TEAM_DEFAULTS,
  VISIBILITY_OPTIONS,
  THEME_OPTIONS,
LANGUAGE_OPTIONS,
PREFERENCES_DEFAULTS,
ACTIVITY_MESSAGES: {},
  ADMIN_MESSAGES: {},
  ARCHIVE_DEFAULTS: {},
  BACKUP_MESSAGES: {},
  BOOKMARK_MESSAGES: {},
  CATEGORY_MESSAGES: {},
  COMMENT_CONTENT: {},
  DASHBOARD_MESSAGES: {},
  DEBUG_MESSAGES: {},
  INFRA_MESSAGES: {},
  LOG_LEVELS: {},
  NOTIFICATION_MESSAGES: {},
  PREFERENCES_MESSAGES: {},
  RECOMMENDATION_DEFAULTS: {},
  REVIEW_MESSAGES: {},
  SESSION_STATUS: {},
  SETTINGS_DEFAULTS: {},
  TAG_MESSAGES: {},
  TEAM_MESSAGES: {},
  USER_MESSAGES: {},
  WORKFLOW_MESSAGES: {},
};
