const INFRA_CONFIG = {
  PAGINATION: {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 10,
    MAX_LIMIT: 50,
  },
  SEARCH: {
    MIN_QUERY_LENGTH: 2,
    MAX_RESULTS: 20,
  },
  CACHE: {
    TTL: 300, 
  },
  VALIDATION: {
    TITLE_MIN_LENGTH: 3,
    TITLE_MAX_LENGTH: 100,
    DESCRIPTION_MAX_LENGTH: 1000,
    TAGS_MAX_COUNT: 10,
  },
  RATE_LIMIT: {
    WINDOW_MS: 15 * 60 * 1000, 
    MAX_REQUESTS: 100,
  },
};

module.exports = INFRA_CONFIG;